### ISSUE TITLE
Naming User-facing xmap functions

### ISSUE THREAD

**Issue by emitanaka** [cynthiahqy/conformr#54]
- I think the prefix should be `xmap_`, e.g. `xmap_validate()`, rather than `validate_xmap()` where the first argument is an `xmap`.
- Subsequently, the first argument of `xmap_apply(xmap = ..., data = ...)` while another function say `apply_xmap(data = ..., xmap = ...)` can have it other way around. 

 - "apply" still questionable though and I don't recommend it as R has a suite of apply functions (`tapply`, `sapply`, `apply`) that is not related to this
 - maybe `xmap_join()` or `xmap_merge()`

**Comment by cynthiahqy** [comment]
Rob suggested `create_xmap()`, `validate_xmap()` and `apply_xmap()` as a pipeline. However, only `apply_xmap()` naturally forms a function, since the actual steps taken in the create/validate steps will vary depending on the application.

Could also offer two functions for applying transformation (data first, xmap first versions)

**Comment by cynthiahqy** [comment]
# Naming Principles
- any that could take any type of `xmap` should be named using the `xmap_` prefix convention -- e.g. `xmap_has_*()` property validators.
- functions specific to subclass end with the `_<subclass>` suffix, and/or named as S3 dispatch method (i.e. `<generic>.<subclass>`).
- functions should probably never end in `_xmap()` because it's not clear which subclass they act on.

## Construction and Coercion
- `new_xmap()` is an alias for `new_xmap_df()` -- pushes user to use df format for xmap. Could this cause problems/ambiguity later when creating other subclasses (e.g. `xmap_graph` or `xmap_matrix`)?

## Validation functions
- generics that will form part of a user workflow should follow the `xmap_` prefix convention (e.g. `xmap_validate()`). Also makes reduces ambiguity when using these functions in a conformr workflow.
- validation functions currently named using a suffix convention `validate_xmap_df()` get called by the method (`xmap_validate.xmap_df()`)

**Comment by cynthiahqy** [comment]
- [ ] fix inconsistency with `x` argument where it sometimes refers to an `xmap` (i.e. in `xmap_validate()`), or a data.frame-like object `as_xmap_df()`
